[package]
name = "rust_wasm_debug"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.8.8", features = ["csr", "nightly"] }
log = "0.4.28"
